# Generated by Django 5.2.7 on 2026-04-23 21:01

from django.db import migrations
from os import getenv
from django.contrib.auth.hashers import make_password

def create_admin_account(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AdminProfile = apps.get_model("tutor", "AdminProfile")

    username = getenv("ADMIN_USER") or "admin"
    email = getenv("ADMIN_EMAIL") or "admin@example.com"
    password = getenv("ADMIN_PASS") or "password1234"

    user, created = User.objects.get_or_create(
        username=username,
        defaults={
            "email": email,
            "password": make_password(password),
            "is_staff": True,
            "is_superuser": True,
            "is_active": True,
        },
    )

    changed = False

    if email and user.email != email:
        user.email = email
        changed = True

    if not user.is_staff:
        user.is_staff = True
        changed = True

    if not user.is_superuser:
        user.is_superuser = True
        changed = True

    if not user.is_active:
        user.is_active = True
        changed = True

    AdminProfile.objects.get_or_create(user=user)

    if changed:
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_admin_account),
    ]