# Generated by Django 5.2.7 on 2025-12-02 01:25

from django.db import migrations
from tutor.models import AdminProfile
from os import getenv

def create_admin_account(apps, schema_editor):
    User = apps.get_model("auth", "User")

    username = getenv("ADMIN_USER") or "admin"
    email = getenv("ADMIN_EMAIL") or "admin@example.com"
    password = getenv("ADMIN_PASS") or "password1234"

    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(
            username=username,
            email=email,
            password=password,
        )

    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return 

    AdminProfile.objects.get_or_create(user=user)


# python manage.py migrate
class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_account),
    ]
