# Generated by Django 5.2.7 on 2025-12-03 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_quiz_adminprofile_quizanswer_session_quiz_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='tutor.teacherprofile'),
        ),
    ]
