# Generated by Django 5.2.7 on 2025-12-04 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_studentprofile_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_completion_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Weighted completion based on quiz scores and session activity', max_digits=5)),
                ('current_module', models.CharField(blank=True, help_text='Current topic/module - inferred from most recent session title', max_length=200)),
                ('quiz_average', models.DecimalField(blank=True, decimal_places=2, help_text='Average quiz score across all graded quizzes', max_digits=5, null=True)),
                ('activity_streak', models.IntegerField(default=0, help_text='Consecutive days with at least one activity')),
                ('last_activity', models.DateTimeField(blank=True, help_text='Timestamp of most recent chat or quiz activity', null=True)),
                ('total_sessions', models.IntegerField(default=0, help_text='Total number of chat sessions created')),
                ('total_quizzes', models.IntegerField(default=0, help_text='Total number of quizzes completed')),
                ('total_messages', models.IntegerField(default=0, help_text='Total number of user messages sent')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Progress',
                'indexes': [models.Index(fields=['user', 'updated_at'], name='tutor_stude_user_id_1b0b06_idx')],
            },
        ),
    ]
