# Generated by Django 5.2.7 on 2026-02-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='earned_pts',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='possible_pts',
            field=models.FloatField(default=0.0),
        ),
    ]
