# Generated by Django 5.2.7 on 2026-03-09 00:00

from django.db import migrations, models


def _best_display_name(user):
    first_name = (getattr(user, "first_name", "") or "").strip()
    last_name = (getattr(user, "last_name", "") or "").strip()
    full_name = f"{first_name} {last_name}".strip()
    if full_name:
        return full_name

    username = (getattr(user, "username", "") or "").strip()
    if username:
        return username

    email = (getattr(user, "email", "") or "").strip()
    if email:
        return email

    return str(getattr(user, "pk", ""))


def backfill_profile_display_names(apps, schema_editor):
    profile_model_names = ("StudentProfile", "TeacherProfile", "AdminProfile")
    for model_name in profile_model_names:
        Profile = apps.get_model("tutor", model_name)
        for profile in Profile.objects.select_related("user").all().iterator():
            if (profile.display_name or "").strip():
                continue
            profile.display_name = _best_display_name(profile.user)
            profile.save(update_fields=["display_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0006_quiz_earned_pts_quiz_possible_pts"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(backfill_profile_display_names, migrations.RunPython.noop),
    ]
